ARMiniCore/Models/ErrorViewModel.cs
namespace ARMiniCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ARMiniCore/Models/MiniCoreModel.cs
using ARMiniCore.Data.Models;

namespace ARMiniCore.Models
{
    public class MiniCoreModel
    {
        public List<Usuario> Usuarios { get; set; }
        public List<Pase> Pases { get; set; }
        public List<UsuarioPase> UsuarioPases { get; set; }
        public DateTime FechaSeleccionada { get; set; }

    }
}

ARMiniCore/Controllers/HomeController.cs
using ARMiniCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ARMiniCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ARMiniCore/Controllers/MiniCoreController.cs
using ARMiniCore.Data.Models;
using ARMiniCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ARMiniCore.Controllers
{
    public class MiniCoreController : Controller
    {
        private DataBaseContext _context;

        public MiniCoreController(DataBaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            MiniCoreModel miniCoreModel = new MiniCoreModel();

            miniCoreModel = calcularFechas(DateTime.Now.Date);
             
            return View(miniCoreModel);
        }

        [HttpPost]
        public IActionResult Index(DateTime fechaSeleccionada)
        {
            
            MiniCoreModel miniCoreModel = new MiniCoreModel();
            miniCoreModel = calcularFechas(fechaSeleccionada);
            return View(miniCoreModel);
        }

        private MiniCoreModel calcularFechas(DateTime fechaCalcular)
        {
            MiniCoreModel miniCoreModel = new MiniCoreModel();

            List<UsuarioPase> usuarioPasesVigentes = new List<UsuarioPase>();

            usuarioPasesVigentes = (from up in _context.UsuarioPase
                                    join us in _context.Usuario on up.UsuarioId equals us.UsuarioId
                                    join pa in _context.Pase on up.PaseId equals pa.PaseId
                                    where DateTime.Compare(fechaCalcular, up.FechaExpiracion) <= 0
                                    && DateTime.Compare(fechaCalcular, up.FechaCompra) >= 0
                                    select new UsuarioPase
                                    {
                                        FechaExpiracion = up.FechaExpiracion,
                                        FechaCompra = up.FechaCompra,
                                        PaseId = up.PaseId,
                                        UsuarioId = up.UsuarioId,
                                        Usuario = us,
                                        Pase = new Pase
                                        {
                                            PaseId = pa.PaseId,
                                            TipoPase = pa.TipoPase,
                                            Costo = pa.Costo,
                                            Pases = pa.Pases,
                                            CostoPase = pa.CostoPase
                                        }
                                    }).ToList();

            var usuariosVigentes = (from us in _context.Usuario.ToList()
                                    join up in usuarioPasesVigentes on us.UsuarioId equals up.UsuarioId
                                    select us).Distinct().ToList();

            var pases = _context.Pase.ToList();


            foreach (var item in usuarioPasesVigentes)
            {
                var paseComprado = pases.Where(p => p.PaseId == item.PaseId).FirstOrDefault();
                if (paseComprado != null)
                {
                    var numeroPases = paseComprado.Pases;
                    var numeroPasesConsumidos = (fechaCalcular - item.FechaCompra).Days;
                    item.Pase.Pases = numeroPases - numeroPasesConsumidos;
                }
            }

            miniCoreModel.Usuarios = usuariosVigentes;
            miniCoreModel.Pases = pases;
            miniCoreModel.UsuarioPases = usuarioPasesVigentes;

            return miniCoreModel;
        }
    }
}

ARMiniCore/Controllers/PasesController.cs
using ARMiniCore.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ARMiniCore.Controllers
{
    public class PasesController : Controller
    {
        private DataBaseContext _context;

        public PasesController(DataBaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var pases = _context.Pase.ToList();
            return View(pases);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Pase nuevoPase)
            {
            _context.Pase.Add(nuevoPase);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ARMiniCore/Controllers/UsuarioPasesController.cs
using ARMiniCore.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ARMiniCore.Controllers
{
    public class UsuarioPasesController : Controller
    {

        private DataBaseContext _context;

        public UsuarioPasesController(DataBaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var usuarioPases = (from up in _context.UsuarioPase
                                join us in _context.Usuario on up.UsuarioId equals us.UsuarioId
                                join pa in _context.Pase on up.PaseId equals pa.PaseId
                                select new UsuarioPase
                                {
                                    UsuarioId = up.UsuarioId,
                                    PaseId = up.PaseId,
                                    FechaCompra = up.FechaCompra,
                                    FechaExpiracion = up.FechaExpiracion,
                                    Usuario = us,
                                    Pase = pa
                                }).ToList();

            return View(usuarioPases);
        }

        public IActionResult Create()
        {
            ViewBag.UsuarioId = new SelectList(_context.Usuario, "UsuarioId", "Nombre");
            ViewBag.PaseId = new SelectList(_context.Pase, "PaseId", "TipoPase");
            return View();
        }

        [HttpPost]
        public IActionResult Create(UsuarioPase nuevoUsuarioPase)
        {
            var nuevoUsuarioPaseId = nuevoUsuarioPase.PaseId;
            var tipoPase = _context.Pase.Where(p => p.PaseId == nuevoUsuarioPaseId).FirstOrDefault();
            if (tipoPase != null)
            {
                var fechaCompra = nuevoUsuarioPase.FechaCompra;
                var fechaExpiracion = fechaCompra.AddDays(tipoPase.Pases);
                nuevoUsuarioPase.FechaExpiracion = fechaExpiracion;
                _context.UsuarioPase.Add(nuevoUsuarioPase);
                _context.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

ARMiniCore/Controllers/UsuariosController.cs
using ARMiniCore.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace ARMiniCore.Controllers
{
    public class UsuariosController : Controller
    {
        private DataBaseContext _context;

        public UsuariosController(DataBaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var usuarios = _context.Usuario.ToList();
            return View(usuarios);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario nuevoUsuario)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Error";
                return View(nuevoUsuario);
            }
            _context.Usuario.Add(nuevoUsuario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ARMiniCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ARMiniCore/Views/MiniCore/Index.cshtml
@model ARMiniCore.Models.MiniCoreModel

@{
    ViewData["Title"] = "Logica de negocio";
}

@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            ViewBag.Error
        </div>
    </div>
}
<br />
<br />

@if (Model.Usuarios.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Correo</th>
                    <th>Fecha de nacimiento</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Usuarios)
                {
                    <tr class="align-middle">
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            @item.Correo
                        </td>
                        <td>
                            @item.FechaNacimiento.ToShortDateString()
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container">
        <div class="alert alert-primary">
            <h2>No existen registros de usuarios</h2>
        </div>
    </div>
}


@if (Model.Pases.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th>Tipo de Pase</th>
                    <th>Costo Pase</th>
                    <th>Pases</th>
                    <th>Costo Pase</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Pases)
                {
                    <tr class="align-middle">
                        <td>
                            @item.TipoPase
                        </td>
                        <td>
                            @item.Costo
                        </td>
                        <td>
                            @item.Pases
                        </td>
                        <td>
                            @item.CostoPase
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container">
        <div class="alert alert-primary">
            <h2>No existen registros de pases</h2>
        </div>
    </div>
}

<div class="container my-2">
    @using (Html.BeginForm())
    {
        <div>
            <h3>Seleccione una fecha</h3>
            @Html.TextBoxFor(model=>model.FechaSeleccionada, new{Type = "date"})
            <input type="submit" value="Calcular">
        </div>
    }
</div>

@if (Model.UsuarioPases.Count > 0)
{
    <div class="container">
        <div class="table-responsive">
            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <th>Nombre de usuario</th>
                        <th>Tipo de Pase</th>
                        <th>Número de pases restantes</th>
                        <th>Fecha de compra</th>
                        <th>Fecha de expiración</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.UsuarioPases)
                    {
                        <tr class="align-middle">
                            <td>
                                @item.Usuario.Nombre
                            </td>
                            <td>
                                @item.Pase.TipoPase
                            </td>
                            <td>
                                @item.Pase.Pases
                            </td>
                            <td>
                                @item.FechaCompra.ToShortDateString()
                            </td>
                            <td>
                                @item.FechaExpiracion.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="alert alert-primary">
            <h2>No existen registros de pases comprados</h2>
        </div>
    </div>
}

ARMiniCore/Views/Pases/Create.cshtml
@model ARMiniCore.Data.Models.Pase
@{
    ViewData["Title"] = "Crear Pase";
}
<h2>Crear Usuario</h2>
@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            @ViewBag.Error
        </div>
    </div>
}
<div class="container">
    @using (Html.BeginForm())
    {
        <div>
            <p>Tipo de pase</p>
            @Html.EditorFor(model => model.TipoPase)
        </div>
        <div>
            <p>Costo</p>
            @Html.EditorFor(model => model.Costo)
        </div>
        <div>
            <p>Cantidad de pases</p>
            @Html.EditorFor(model => model.Pases)
        </div>
        <div>
            <p>Costo individual de pase</p>
            @Html.EditorFor(model => model.CostoPase)
        </div>
        <input values:"Crear" type="submit" />
    }
</div>

ARMiniCore/Views/Pases/Index.cshtml
@model List<ARMiniCore.Data.Models.Pase>

@{
    ViewData["Title"] = "Pases";
}
<a class="btn btn-primary" href="@Url.Action("Create")">Crear pase</a>

@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            @ViewBag.Error
        </div>
    </div>
}
<br />
<br />

@if (Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th>Tipo de Pase</th>
                    <th>Costo Pase</th>
                    <th>Pases</th>
                    <th>Costo Pase</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="align-middle">
                        <td>
                            @item.TipoPase
                        </td>
                        <td>
                            @item.Costo
                        </td>
                        <td>
                            @item.Pases
                        </td>
                        <td>
                            @item.CostoPase
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>
        <h2>No existen registros</h2>
    </div>
}

ARMiniCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ARMiniCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ARMiniCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Alain Ruales - MiniCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pases" asp-action="Index">Pases</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UsuarioPases" asp-action="Index">Comprar pases</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MiniCore" asp-action="Index">MiniCore</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ARMiniCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ARMiniCore/Views/UsuarioPases/Create.cshtml
@model ARMiniCore.Data.Models.UsuarioPase
@{
    ViewData["Title"] = "Agregar pase a usuario";
}
<h2>Crear Usuario</h2>
@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            @ViewBag.Error
        </div>
    </div>
}
<div class="container">
    @using (Html.BeginForm())
    {
        <div>
            <p>Seleccione un usuario</p>
            @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control" })
        </div>
        <div>
            <p>Seleccione tipo de pase</p>
            @Html.DropDownList("PaseId", null, htmlAttributes: new { @class = "form-control" })
        </div>
        <div>
            <p>Fecha de compra</p>
            @Html.TextBoxFor(model=>model.FechaCompra, new{Type = "date"})
        </div>
        <input values:"Crear" type="submit" />
    }
</div>

ARMiniCore/Views/UsuarioPases/Index.cshtml
@model List<ARMiniCore.Data.Models.UsuarioPase>

@{
    ViewData["Title"] = "Pases comprados";
}
<a class="btn btn-primary" href="@Url.Action("Create")">Crear pase</a>

@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            ViewBag.Error
        </div>
    </div>
}
<br />
<br />

@if (Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th>Nombre de usuario</th>
                    <th>Tipo de Pase</th>
                    <th>Número de pases</th>
                    <th>Fecha de compra</th>
                    <th>Fecha de expiración</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="align-middle">
                        <td>
                            @item.Usuario.Nombre
                        </td>
                        <td>
                            @item.Pase.TipoPase
                        </td>
                        <td>
                            @item.Pase.Pases
                        </td>
                        <td>
                            @item.FechaCompra.ToShortDateString()
                        </td>
                        <td>
                            @item.FechaExpiracion.ToShortDateString()
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>
        <h2>No existen registros</h2>
    </div>
}

ARMiniCore/Views/Usuarios/Create.cshtml
@model ARMiniCore.Data.Models.Usuario
@{
    ViewData["Title"] = "Crear Usuario";
}
<h2>Crear Usuario</h2>
@if (ViewBag.Error != null)
{
    <div class="container">
        <div class="alert alert-primary">
            @ViewBag.Error
        </div>
    </div>
}
<div class="container">
    @using (Html.BeginForm())
    {
        <div>
            <p>Nombre de usuario</p>
            @Html.TextAreaFor(model => model.Nombre)
        </div>
        <div>
            <p>Correo de usuario</p>
            @Html.TextAreaFor(model => model.Correo)
        </div>
        <div>
            <p>Fecha de nacimiento de usuario</p>
            @Html.TextBoxFor(model=>model.FechaNacimiento, new{Type = "date"})
        </div>
        <div>
            <p>Contraseña</p>
            @Html.PasswordFor(model => model.Clave)
        </div>
        <input values:"Crear" type="submit" />
    }
</div>

ARMiniCore/Views/Usuarios/Index.cshtml
@model List<ARMiniCore.Data.Models.Usuario>

@{
    ViewData["Title"] = "Usuarios";
}
@Html.ActionLink("Crear Usuario","Create",new{@class="btn-primary"})

@if (ViewBag.Error == "Error")
{
    <div class="container">
        <div class="alert alert-primary">
            Se ha producido un error
        </div>
    </div>
}
<br />
<br />

@if (Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Correo</th>
                    <th>Fecha de nacimiento</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="align-middle">
                        <td>
                            @item.UsuarioId
                        </td>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            @item.Correo
                        </td>
                        <td>
                            @item.FechaNacimiento.ToShortDateString()
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>
        <h2>No existen registros</h2>
    </div>
}